db_name: db.sqllite3
path:
  raw_data: data_source
  prepare_data: prepare_data
tables:
  lap_times:
    db_table_name: stats_laptime
    column:
      raceId: race_id
      driverId: driver_id
      lap: lap_no
      position: position
      time: time
      milliseconds: time_ms
  drivers:
    db_table_name: stats_driver
    column:
      driverId: id
      driverRef: driver_id
      lap: lap_no
      position: position
      time: time
      milliseconds: time_ms