db_name: C:/py_project/fdata/db.sqlite3
path:
  raw_data: data_source
  prepare_data: prepare_data
tables:
  drivers:
    db_table_name: stats_driver
    model_name: Driver
    column:
      driverId: id
      driverRef: short_name
      forename: first_name
      surname: last_name
      dob: birthdate
      nationality: nationality
      url: url
